baseURL: https://monica-gerber.netlify.app/
languageCode: en-us
paginate: 6
theme: portio-hugo
title: Monica Gerber Plüss
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Projects
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
    - name: Publications
      url: '#blog'
      weight: 6
    - name: Research lines
      url: '#service'
      weight: 7
    - name: Contact
      url: '#contact'
      weight: 8
  sitemap:
    - name: About me
      url: about
      weight: 1
    - name: Latest Article
      url: 'blog'
      weight: 2
params:
  # address:
  #   address: 23 Khan Niketon, Grand Street, NYK.
  #   email: hello@example.com
  #   openingHours: Open from 10am to 6pm (close at 5pm Sundays)
  #   phone: +(448) 833 5272 332
  blogPageURL: blog
  contactLink: contact
  copyright: All right reserved copyright ©
  footerLogo: images/contact/widget-logo.png
  formspreeURL: YOUR FORMSPREE URL
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo.png
  # map:
  #   APIkey: YOUR GOOGLE MAP API
  #   latitude: '23.7783741'
  #   longitude: '90.3746808'
  #   pinImage: images/pin.png
  social:
    - icon: fa-book
      url: https://scholar.google.co.uk/citations?user=4L5fnNEAAAAJ&hl=en
      weight: 1
    - icon: fa-pencil
      url: https://www.researchgate.net/profile/Monica-Gerber
      weight: 2
    - icon: fa-twitter-square
      url: https://twitter.com/monica_gerber/
      weight: 3
